// vue-client/src/views/Home.vue
<template>
  <div>
    <div class="row">
      <div class="col-4">
        <h5>Hottest Post</h5>
        <span v-if="$apollo.queries.hottestPost.loading">
          Loading...
        </span>
        <post-card v-else
            :title="hottestPost.title"
            :author="hottestPost.author.email"
            :content="hottestPost.content"
            :thumbs-down="hottestPost.thumbsDown"
            :thumbs-up="hottestPost.thumbsUp"
            @voteUp="voteUp(hottestPost.id)"
            @voteDown="voteDown(hottestPost.id)">
        </post-card>
      </div>
      <div class="col">
        <post-card  v-for="post in posts"
            :key="post.id"
            :title="post.title"
            :author="post.author.email"
            :content="post.content"
            :thumbs-down="post.thumbsDown"
            :thumbs-up="post.thumbsUp"
            @voteUp="voteUp(post.id, post.thumbsUp)"
            @voteDown="voteDown(post.id)">
        </post-card>
        <post-form @submitForm="addNewPost">
        </post-form>
      </div>
    </div>
  </div>
</template>

<script>
import PostCard from '@/components/PostCard.vue';
import PostForm from '@/components/PostForm.vue';
import GetPostsQuery from '@/graphql/GetPosts.graphql';
import GetHottestPostQuery from '@/graphql/GetHottestPost.graphql';
import VoteUpMutation from '@/graphql/VoteUp.graphql';
import VoteDownMutation from '@/graphql/VoteDown.graphql';
import AddPostMutation from '@/graphql/AddPost.graphql';

export default {
  name: 'home',
  components: {
    PostCard,
    PostForm,
  },
  apollo: {
    posts: {
      query: GetPostsQuery,
      update(data) {
        return data.getPosts;
      },
    },
    hottestPost: {
      query: GetHottestPostQuery,
      update(data) {
        return data.getHottestPost;
      },
    },
  },
  methods: {
    voteUp(postId, thumbsUp) {
      this.$apollo.mutate({
        mutation: VoteUpMutation,
        optimisticResponse: {
          voteUp: {
            __typename: 'Post',
            id: postId,
            thumbsUp: thumbsUp + 1,
          },
        },
        variables: {
          postId,
        },
      });
    },
    voteDown(postId) {
      this.$apollo.mutate({
        mutation: VoteDownMutation,
        variables: {
          postId,
        },
      });
    },
    addNewPost(form) {
      this.$apollo.mutate({
        mutation: AddPostMutation,
        variables: {
          title: form.title,
          content: form.content,
        },
        update: (store, { data: { addPost } }) => {
          const data = store.readQuery({ query: GetPostsQuery });
          data.getPosts.push(addPost);
          store.writeQuery({ query: GetPostsQuery, data });
        },
      });
    },
  },
};
</script>

// angular-client/src/app/home/home.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import { Apollo } from 'apollo-angular';
import { GET_HOTTEST_POST, GET_POSTS } from '../graphql/queries';
import { Subscription } from 'rxjs';
import {ADD_POST, VOTE_DOWN, VOTE_UP} from '../graphql/mutations';
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit, OnDestroy {
  private getPostsSubscription: Subscription;
  private getHottestPostSubscription: Subscription;

  public posts: any;
  public hottestPost: any;
  public hottestPostLoading: boolean;

  constructor(private readonly apollo: Apollo) { }

  ngOnInit() {
    this.hottestPostLoading = true;

    this.getPostsSubscription = this.apollo
      .watchQuery({
        query: GET_POSTS,
      })
      .valueChanges
      .subscribe(({ data }: any) => {
        this.posts = data.getPosts;
      });

    this.getHottestPostSubscription = this.apollo
      .watchQuery({
        query: GET_HOTTEST_POST,
      })
      .valueChanges
      .subscribe(({ data }: any) => {
        this.hottestPostLoading = data.loading;
        this.hottestPost = data.getHottestPost;
      });
  }

  ngOnDestroy() {
    this.getPostsSubscription.unsubscribe();
  }


  onVoteDown(postId: number) {
    this.apollo.mutate({
      mutation: VOTE_DOWN,
      variables: {
        postId
      },
    }).subscribe();
  }

  onVoteUp(postId: number, thumbsUp: number) {
    this.apollo.mutate({
      mutation: VOTE_UP,
      variables: {
        postId
      },
      optimisticResponse: {
        voteUp: {
          __typename: 'Post',
          id: postId,
          thumbsUp: thumbsUp + 1,
        },
      },
    }).subscribe();
  }

  addNewPost(newPost) {
    this.apollo.mutate({
      mutation: ADD_POST,
      variables: newPost,
      update: (store, { data }) => {
        const getPostCache: any = store.readQuery({ query: GET_POSTS });
        getPostCache.getPosts.push(data.addPost);
        store.writeQuery({
          query: GET_POSTS,
          data: getPostCache,
        });
      }
    }).subscribe();
  }
}

<div>
  <div class="row">
    <div class="col-4">
      <h5>Hottest Post</h5>
      <span *ngIf="hottestPostLoading; else hottestPostCard"> Loading... </span>
      <ng-template #hottestPostCard>
        <app-post-card *ngIf="!hottestPostLoading"
            [title]="hottestPost.title"
            [author]="hottestPost.author.email"
            [content]="hottestPost.content"
            [thumbsDown]="hottestPost.thumbsDown"
            [thumbsUp]="hottestPost.thumbsUp"
            (voteUp)="onVoteUp(hottestPost.id)"
            (voteDown)="onVoteDown(hottestPost.id)">
        </app-post-card>
      </ng-template>
    </div>
    <div class="col">
      <app-post-card *ngFor="let post of posts"
          [title]="post.title"
          [author]="post.author.email"
          [content]="post.content"
          [thumbsDown]="post.thumbsDown"
          [thumbsUp]="post.thumbsUp"
          (voteUp)="onVoteUp(post.id, post.thumbsUp)"
          (voteDown)="onVoteDown(post.id)">
      </app-post-card>
      <app-post-form (submitForm)="addNewPost($event)"> </app-post-form>
    </div>
  </div>
</div>
