// vue-client/src/components/PostCard.vue
<template>
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title">{{ title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">{{ author }}</h6>
      <p class="card-text">
        {{ content }}
      </p>
    </div>
    <div class="card-footer">
      <div class="row">
        <div class="col-6 text-center">
          <button class="btn btn-block btn-danger"
              @click="$emit('voteDown')">
          <i class="far fa-thumbs-down"></i>
            {{ thumbsDown }}
          </button>
        </div>
        <div class="col-6 text-center">
          <button class="btn btn-block btn-success"
              @click="$emit('voteUp')">
            <i class="far fa-thumbs-up"></i>
            {{ thumbsUp }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'PostCard',
  props: {
    title: String,
    author: String,
    content: String,
    thumbsUp: Number,
    thumbsDown: Number,
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>

// react-client/src/components/PostCard.js
import React from 'react';

function PostCard(props) {
  return (
    <div className="card mb-3">
      <div className="card-body">
        <h5 className="card-title">{ props.title }</h5>
        <h6 className="card-subtitle mb-2 text-muted">{ props.author }</h6>
        <p className="card-text">
          { props.content }
        </p>
      </div>
      <div className="card-footer">
        <div className="row">
          <div className="col-6 text-center">
            <button className="btn btn-block btn-danger" onClick={props.thumbsDownClick}>
              <i className="far fa-thumbs-down"></i>
              { props.thumbsDown }
            </button>
          </div>
          <div className="col-6 text-center">
            <button className="btn btn-block btn-success" onClick={props.thumbsUpClick}>
            <i className="far fa-thumbs-up"></i>
              { props.thumbsUp }
            </button>
          </div>
        </div>
      </div>
    </div>
);

}

export default PostCard;
