// vue-client/src/components/PostForm.vue
<template>
  <div class="card mb-3">
    <div class="card-body">
      <form @submit.prevent="submitForm">
        <div class="form-group">
          <label for="title">Title:</label>
          <input type="text" v-model="title" class="form-control" id="title" required>
        </div>
        <div class="form-group">
          <label for="content">Content:</label>
          <textarea class="form-control"
              v-model="content"
              id="content"
              rows="3"
              required>
          </textarea>
        </div>
        <button type="submit"
            class="btn btn-primary btn-block">
          Add new post
        </button>
      </form>
    </div>
  </div>
</template>

<script>
export default {
  name: 'PostForm',
  data() {
    return {
      title: '',
      content: '',
    };
  },
  methods: {
    submitForm() {
      const form = { title: this.title, content: this.content };
      this.$emit('submitForm', form);
    },
  },
};
</script>

<style scoped>

</style>

// angular-client/src/app/shared/post-form/post-form.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-post-form',
  templateUrl: './post-form.component.html',
  styleUrls: ['./post-form.component.scss']
})
export class PostFormComponent implements OnInit {
  @Output()
  private readonly submitForm = new EventEmitter();

  public form: FormGroup;

  constructor(private readonly fb: FormBuilder) {
    this.form = this.fb.group(
      {
        title: [ '' ],
        content: [ '' ],
      },
    );
  }

  ngOnInit() {
  }

  addPost() {
    this.submitForm.next(this.form.value);
  }
}

<div class="card mb-3">
  <div class="card-body">
    <form [formGroup]="form" (submit)="addPost()">
      <div class="form-group">
        <label for="title">Title:</label>
        <input formControlName="title"
            type="text"
            class="form-control"
            id="title"
            required/>
      </div>
      <div class="form-group">
        <label for="content">Content:</label>
        <textarea formControlName="content"
            class="form-control"
            id="content"
            rows="3"
            required>
        </textarea>
      </div>
      <button type="submit" class="btn btn-primary btn-block">
        Add new post
      </button>
    </form>
  </div>
</div>
