// angular-client/src/app/shared/post-card/post-card.component.ts
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';

@Component({
  selector: 'app-post-card',
  templateUrl: './post-card.component.html',
  styleUrls: ['./post-card.component.scss']
})
export class PostCardComponent implements OnInit {
  @Input()
  public readonly title: string;
  @Input()
  public readonly author: string;
  @Input()
  public readonly content: string;
  @Input()
  public readonly thumbsUp: number;
  @Input()
  public readonly thumbsDown: number;
  @Output()
  private readonly voteUp = new EventEmitter();
  @Output()
  private readonly voteDown = new EventEmitter();

  constructor() { }

  ngOnInit() {
  }
}

<div class="card mb-3">
  <div class="card-body">
    <h5 class="card-title">{{ title }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ author }}</h6>
    <p class="card-text">
      {{ content }}
    </p>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col-6 text-center">
        <button class="btn btn-block btn-danger"
                (click)="voteDown.emit()">
          <i class="far fa-thumbs-down"></i>
          {{ thumbsDown }}
        </button>
      </div>
      <div class="col-6 text-center">
        <button class="btn btn-block btn-success"
                (click)="voteUp.emit()">
          <i class="far fa-thumbs-up"></i>
          {{ thumbsUp }}
        </button>
      </div>
    </div>
  </div>
</div>

// vue-client/src/components/PostCard.vue
<template>
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title">{{ title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">{{ author }}</h6>
      <p class="card-text">
        {{ content }}
      </p>
    </div>
    <div class="card-footer">
      <div class="row">
        <div class="col-6 text-center">
          <button class="btn btn-block btn-danger"
              @click="$emit('voteDown')">
          <i class="far fa-thumbs-down"></i>
            {{ thumbsDown }}
          </button>
        </div>
        <div class="col-6 text-center">
          <button class="btn btn-block btn-success"
              @click="$emit('voteUp')">
            <i class="far fa-thumbs-up"></i>
            {{ thumbsUp }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'PostCard',
  props: {
    title: String,
    author: String,
    content: String,
    thumbsUp: Number,
    thumbsDown: Number,
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
