// react-client/src/components/NavBar.js
import React from 'react';
import {Link} from "react-router-dom";
import { onLogout, isLoggedIn } from "../react-apollo";
import UserInfo from "./UserInfo";
import { withRouter } from 'react-router-dom'

function NavBar(props) {
  function logout() {
    props.history.push('/login');
    onLogout();
  };

  return (
    <nav className="navbar navbar-dark bg-primary justify-content-between">
      <div className="container">
        <Link className="navbar-brand" to="/">Microblog</Link>
        {isLoggedIn() ? (
          <div className="d-flex">
            <UserInfo></UserInfo>
            <button className="btn navbar-link" onClick={logout}>
              Logout
            </button>
          </div>) : null
        }
      </div>
    </nav>
  );

}

export default withRouter(NavBar);

// angular-client/src/app/shared/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import {AuthService} from "../../core/services/auth.service";

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent implements OnInit {

  constructor(private readonly authService: AuthService) { }

  ngOnInit() {
  }

  get isLoggedIn() {
    return this.authService.isLoggedIn();
  }

  logout() {
    this.authService.logout();
  }
}

<nav class="navbar navbar-dark bg-primary justify-content-between">
  <div class="container">
    <a class="navbar-brand" routerLink="/">Microblog</a>
    <div *ngIf="isLoggedIn" class="d-flex">
      <app-user-info></app-user-info>
      <button class="btn navbar-link" (click)="logout()">
        Logout
      </button>
    </div>
  </div>
</nav>
